### ISSUE TITLE
Possible missing data when using objects

### ISSUE THREAD

**Issue by Luna-Klatzer** [Luna-Klatzer/openhiven.py#48]
**Issue:**
Currently, in OpenHiven.py instances are used to represent Hiven Objects and provide the option to interact with Hiven. This is a core feature of an API Wrapper. Still, with slower speeds (#53) and also sometimes missing data issues can occur when trying to fetch or use data that has not been received yet. This especially can cause headaches since the user does not even notice that until they try to use that data property of the instance.

**Possible Solution:**
- **Automatic Fetching of most recent data when the user fetches an object:**
One straightforward solution would be to implement an automatic request for data when the user gets an item using the Rewrite JSON cache (#53), and data is missing. With that, the user would always receive the most recent data and would overlook the issue. Still, this could lead to slower speeds when fetching an object and slow responsiveness that might not be necessary since the data might not be required.
- **Addition of `fetch_data()` for fetching data if it's missing:**
Another possibility is using a new function that the user can implement to request missing data if some fields are missing (`None`). This would then move the issue away from OpenHiven.py to the user, checking if the data requested even is actually None or missing. This is a rather inefficient and not very smart way of doing this since this can often be overseen and would not benefit the user.
- **Automatic updating of data when accessing a field that might be missing:**
The third solution seems like the best since it combines the two solutions together but automates the process of fetching missing data. Since OpenHiven.py uses `@property` tags for fetching data and their protection this could be also used to fetch missing data if it exists. This would then mean for example with user instances that if they try to access a property that is `None` that OpenHiven.py will request in the background the most recent data and check if it's actually up-to-date and `None`. To not check over and over again there will be then the need for a `complete` property to signalise the data is complete and does not contain missing data. Since if data changes the Hiven Swarm will automatically update the data in the cache making missing data only possible at the very beginning (init-phase) where the Client receives only important data of a user.

**Comment by Nicolas-Klatzer** [comment]
I updated issue according to the new rewrite solution (#54) and the solution and issue not being the same anymore

**Comment by Luna-Klatzer** [comment]
format_obj_data
