### ISSUE TITLE
OpenHiven.py System Rewrite v0.2

### ISSUE THREAD

**Issue by Luna-Klatzer** [Luna-Klatzer/openhiven.py#54]
**Summary:**
The OpenHiven.py System Rewrite is a Rewrite even if early that is necessary to overcome the fundamental issues OpenHiven.py has which are possible memory-leaks, bad class-structure design, bad handling of events, missing option to handle restarts properly, missing option for correct EventListeners and Option for users to optimise EventListening and triggering of events. The Rewrite, therefore, would tackle the core WebSocket, Connection, Storage and EventHandling System but leave the classical system as is. Still, some things might be changed quite heavily to better integrate the changes and take advantage of the new system.

**WebSocket EventHandling in-dept:**
The planned WebSocket and EventHandling System is based on a three-way parallel loop where each part is assigned to handle one part of the WebSocket.
- The first part is the core message handling, which handles the messages and the Exceptions and Restart-Exceptions for incoming messages or close calls. It will be extended by the planned `MessageBroker` and Buffer-System for Events. This system will instead of starting a new background `asyncio.Task` for the event parsers and event listeners (which makes it vulnerable for Memory Leaks), create the event parser task alone and await it's execution, before appending the event data to a `DynamicEventBuffer`, which specifically is used to store all events in a FIFO principle. 
- The second part is the core KeepAlive loop which will likely get updated when Hiven releases a new Swarm Release. This loop is separated to allow it to be independent and modifiable without needing to change handling on any other loop.
- The third part is the most significant new change for the EventHandling since it will be a loop where `Worker` Instances will fetch events from the buffer and execute them separately. This means that there will be one instance of a worker for every event-type that will perform the event handling and trigger and dispatch EventListeners if they are subscribed to the event. Before triggering an event, the worker will likely use validation and the newly integrated JSON-cache as in #53 #55 #46 to construct object instances if needed / an event-listener subscribed expects data. The instances will then get passed to the event listeners but later on 'destroyed' since they are not needed anymore, which means only raw JSON data is stored in the cache without storing entire objects, saving storage and speed up performance.

![Core-OH-Rewrite-Simplified-MessageBroker](https://user-images.githubusercontent.com/61756091/107374763-3a6b4e80-6ae8-11eb-801e-52f4d60b4055.png)
*Logical Plan*

**Restart in-dept:**
Restart Handling is necessary for OpenHiven.py since, without it, it could entirely stop working only if the connection was lost or something interfered with the loops for a short moment. Currently, it's relatively stable but could potentially encounter in the future, if the library is used for bigger Bots, issues with unexpected shutdowns or crashes which are not handled. 

Therefore the current relatively slow and not working restart system needs to be updated in a discord.py way. Restarts are handled over an Exception calling the parent loop to restart the process, which will automatically happen while encountering major exceptions. As an addition, the current restart parameter at the start of running the Client will be used to handle crashes of the entire system where even the Connection Class needs to be recreated and restarted. In such cases, it would then automatically renew the entire process. This would then serve as a rescue option that will default to `False` since for program debugging, always restarting a faulty configuration can damage the debugging-ability. Still, it could significantly improve up-time for production-ready bots by even restarting when the system crashed (this is, of course, limited too if the system cannot interact with Hiven at all). There might be a limit added where too many exceptions in a specific timeframe would stop the program, but likely it will be left to add more logic that might not be useful to the user.

**Rewrite References:**
- #53: Caching Optimisation
- #48: Solution for missing data
- #56: Find Method Generalisation

**Comment by Nicolas-Klatzer** [comment]
**Planned Integration:**
- Parameter Option `run_listeners_queued=True` at Client-Initialisation to specify the running option from either queued or pure parallel. Queued would limit every EventType and their Worker to one event-execution per moment. If a new event is received, it will be queued and not executed directly unless the events before it finished execution. Pure Parallel would mean that every event received is run parallel, leading to heavier memory and CPU usage than queued execution but better latency and responsiveness. The queue does not slow down the process.

**Comment by Luna-Klatzer** [comment]
Implemented with #65
