### ISSUE TITLE
Generalise get_*, fetch_* and find_* functions

### ISSUE THREAD

**Issue by Luna-Klatzer** [Luna-Klatzer/openhiven.py#56]
**Summary:**
Currently, in OpenHiven.py the `get_*` and `fetch_*` functions are used to fetch cached instances, while the `get_*`  functions were supposed to bring the data from the Hiven Server and then return the updated versions of the cached models. 

This was useful since sometimes data was missing and the system was not finished yet, so using the requests as backup seemed like the right solution. Still, after new updates and with the release of version v0.1.3 this will become a deprecated solution since it slows down the finding process and does not utilise the cache as wanted. 

Therefore, a new planned-out system is needed that should align with the planned cache system (#53), where data is not stored anymore in entire instances but instead just in simple plain JSON / dictionary format.

**Planned Generalisation:**
The newly planned system will then use three functions which one of will be entirely new:

* First the standard `get_*` function, which is also used in discord.py to fetch instances. This method will likely stay the same but receive a new system under the hood, where the data is fetched directly from the cache and then returned in the instance form so the user can utilise the function of the class.
* Second the async `fetch_*` function, which will be the updated then used to fetch and request the Hiven Server's data. This function should then be used to fetch data that might be not entirely complete. The function will return the new instance of the requested data.
* Third and last the new `find_*` function, which is a relatively low-level function and will also be used inside the `get_*` function to find the requested object's cached dictionary. The process is relatively simple, and it will simply return a new copied dictionary of the cached data. 

   The function should be used for usage cases where instances and functions are not important and for example only the name or the location of an Hiven object is needed since you only get the raw data and not an instance of the object class. 

   If the user then requires an instance with the data, they can create themselves a new instance of the object based on the data, still for readability and ease it will be recommended to use `get_*` in the first place whenever functions of the class might be needed!

**Comment by Nicolas-Klatzer** [comment]
Added with 01efbdaff216a698f38b4629807a7d924bd56a4f the basic Structure in HivenClient

**Comment by Luna-Klatzer** [comment]
Resolved with #65
